config:
    AZURE_SUBSCRIPTION_ID: "<YOUR-SUBSCRIPTION-ID>" # Please modify to your subscription
    AZURE_RESOURCE_GROUP: "<YOUR-RESOURCE-GROUP>" # Please modify to your Azure resource group
    AZURE_WORKSPACE: "<YOUR-AZURE-WORKSPACE>" # Please modify to your Azure workspace
    AZURE_DATA_NAME: "hf-ultrachat" # Please modify to your AzureML data name
    DATA_DIR: "./dataset"
    CLOUD_DIR: "./cloud"
    HF_MODEL_NAME_OR_PATH: "microsoft/Phi-3.5-mini-instruct"
    IS_DEBUG: true
    USE_LOWPRIORITY_VM: false

train:
    use_builtin_env: true
    azure_env_name: "aml-accelerate" # Please modify to your AzureML env name
    azure_compute_cluster_name: "gpu-cluster"
    azure_compute_cluster_size: "Standard_NC48ads_A100_v4" # A100 (80GB)
    num_training_nodes: 2
    experiment_name: "accelerate-cv-multinode-example"
    epoch: 1
    train_batch_size: 8
    eval_batch_size: 8
    model_dir: "./outputs"
    wandb_api_key: ""
    wandb_project: ""
    wandb_run_name: ""

serve:
    azure_env_name: "llm-serving-2024-11-06" # Please modify to your AzureML env name
    azure_model_name: "multi-node-training-poc-2024-11-06" # Please modify to your AzureML model name
    azure_endpoint_name: "multi-node-endpoint-2024-11-06"
    azure_deployment_name: "blue"
    azure_serving_cluster_size: "Standard_NC6s_v3"
